// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteCategory = `-- name: DeleteCategory :execresult
DELETE FROM categories WHERE "CategoryID" = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, categoryid int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteCategory, categoryid)
}

const getCategories = `-- name: GetCategories :many
SELECT "CategoryID", "CategoryName" FROM categories
`

func (q *Queries) GetCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.CategoryID, &i.CategoryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT "CategoryID", "CategoryName" FROM categories WHERE "CategoryID" = $1
`

func (q *Queries) GetCategory(ctx context.Context, categoryid int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, categoryid)
	var i Category
	err := row.Scan(&i.CategoryID, &i.CategoryName)
	return i, err
}

const insertCategory = `-- name: InsertCategory :execresult
INSERT INTO categories("CategoryName") VALUES($1)
`

func (q *Queries) InsertCategory(ctx context.Context, categoryname string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertCategory, categoryname)
}

const updateCategory = `-- name: UpdateCategory :execresult
UPDATE categories SET "CategoryName" = $1 WHERE "CategoryID" = $2
`

type UpdateCategoryParams struct {
	CategoryName string
	CategoryID   int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateCategory, arg.CategoryName, arg.CategoryID)
}
