// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	CategoryID   int32
	CategoryName string
}

type Expense struct {
	ExpID        int32
	Description  string
	Value        pgtype.Numeric
	StoreID      int32
	CategoryID   int32
	OwnerUserID  int32
	TypeID       int32
	ExpDate      pgtype.Timestamp
	CreationDate pgtype.Timestamp
	PaidOff      pgtype.Bool
	SharesEven   pgtype.Bool
	Qr           string
}

type ExpenseType struct {
	TypeID   int32
	TypeName string
}

type ExpensesPayment struct {
	ExpPaymID int32
	ExpID     int32
	UserID    int32
	Payed     pgtype.Numeric
}

type ExpensesShare struct {
	ExpShareID int32
	ExpID      int32
	UserID     int32
	Share      pgtype.Numeric
	Calculated pgtype.Numeric
}

type SchemaMigration struct {
	Version int64
	Dirty   pgtype.Bool
}

type Store struct {
	StoreID   int32
	StoreName string
	NIF       string
}

type User struct {
	UserID   int32
	UserName string
	UserPass string
}
