// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stores.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteStore = `-- name: DeleteStore :execresult
DELETE FROM stores WHERE "StoreID" = $1
`

func (q *Queries) DeleteStore(ctx context.Context, storeid int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteStore, storeid)
}

const getStore = `-- name: GetStore :one
SELECT "StoreID", "StoreName", "NIF" FROM stores WHERE "StoreID" = $1
`

func (q *Queries) GetStore(ctx context.Context, storeid int32) (Store, error) {
	row := q.db.QueryRow(ctx, getStore, storeid)
	var i Store
	err := row.Scan(&i.StoreID, &i.StoreName, &i.NIF)
	return i, err
}

const getStoreByNIF = `-- name: GetStoreByNIF :one
SELECT "StoreID", "StoreName", "NIF" FROM stores WHERE "NIF" = $1
`

func (q *Queries) GetStoreByNIF(ctx context.Context, nif string) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByNIF, nif)
	var i Store
	err := row.Scan(&i.StoreID, &i.StoreName, &i.NIF)
	return i, err
}

const getStores = `-- name: GetStores :many
SELECT "StoreID", "StoreName", "NIF" FROM stores
`

func (q *Queries) GetStores(ctx context.Context) ([]Store, error) {
	rows, err := q.db.Query(ctx, getStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(&i.StoreID, &i.StoreName, &i.NIF); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStore = `-- name: InsertStore :execresult
INSERT INTO stores("StoreName", "NIF") VALUES($1, $2)
`

type InsertStoreParams struct {
	StoreName string
	NIF       string
}

func (q *Queries) InsertStore(ctx context.Context, arg InsertStoreParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertStore, arg.StoreName, arg.NIF)
}

const updateStore = `-- name: UpdateStore :execresult
UPDATE stores SET "StoreName" = $1, "NIF" = $2 WHERE "StoreID" = $3
`

type UpdateStoreParams struct {
	StoreName string
	NIF       string
	StoreID   int32
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateStore, arg.StoreName, arg.NIF, arg.StoreID)
}
