// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: types.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteType = `-- name: DeleteType :execresult
DELETE FROM "expenseTypes" WHERE "TypeID" = $1
`

func (q *Queries) DeleteType(ctx context.Context, typeid int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteType, typeid)
}

const getType = `-- name: GetType :one
SELECT "TypeID", "TypeName" FROM "expenseTypes" WHERE "TypeID" = $1
`

func (q *Queries) GetType(ctx context.Context, typeid int32) (ExpenseType, error) {
	row := q.db.QueryRow(ctx, getType, typeid)
	var i ExpenseType
	err := row.Scan(&i.TypeID, &i.TypeName)
	return i, err
}

const getTypes = `-- name: GetTypes :many
SELECT "TypeID", "TypeName" FROM "expenseTypes"
`

func (q *Queries) GetTypes(ctx context.Context) ([]ExpenseType, error) {
	rows, err := q.db.Query(ctx, getTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseType
	for rows.Next() {
		var i ExpenseType
		if err := rows.Scan(&i.TypeID, &i.TypeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertType = `-- name: InsertType :execresult
INSERT INTO "expenseTypes"("TypeName") VALUES($1)
`

func (q *Queries) InsertType(ctx context.Context, typename string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertType, typename)
}

const updateType = `-- name: UpdateType :execresult
UPDATE "expenseTypes" SET "TypeName" = $1 WHERE "TypeID" = $2
`

type UpdateTypeParams struct {
	TypeName string
	TypeID   int32
}

func (q *Queries) UpdateType(ctx context.Context, arg UpdateTypeParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateType, arg.TypeName, arg.TypeID)
}
