// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pgsqlc

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT "UserID", "UserName", "UserPass" FROM users WHERE "UserID" = $1
`

func (q *Queries) GetUser(ctx context.Context, userid int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userid)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.UserPass)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT "UserID", "UserName", "UserPass" FROM users WHERE "UserName" = $1
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, username)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.UserPass)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT "UserID", "UserName", "UserPass" FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.UserID, &i.UserName, &i.UserPass); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
