// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type Category struct {
	CategoryID   int64
	CategoryName string
}

type Expense struct {
	ExpID        int64
	Description  string
	Value        string
	StoreID      int64
	CategoryID   int64
	OwnerUserID  int64
	TypeID       int64
	ExpDate      int64
	CreationDate int64
	PaidOff      bool
	SharesEven   bool
}

type ExpenseType struct {
	TypeID   int64
	TypeName string
}

type ExpensesPayment struct {
	ExpPaymID int64
	ExpID     int64
	UserID    int64
	Payed     string
}

type ExpensesShare struct {
	ExpShareID int64
	ExpID      int64
	UserID     int64
	Share      string
	Calculated string
}

type Store struct {
	StoreID   int64
	StoreName string
}

type User struct {
	UserID   int64
	UserName string
	UserPass string
}
