// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shares.sql

package repository

import (
	"context"
	"database/sql"
)

const deleteShare = `-- name: DeleteShare :execresult
DELETE FROM "expensesShares" where "ExpShareID" = ?
`

func (q *Queries) DeleteShare(ctx context.Context, expshareid int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteShare, expshareid)
}

const getShares = `-- name: GetShares :many
SELECT 
  shares.ExpShareID, shares.ExpID, shares.UserID, shares.Share, shares.Calculated, users.UserID, users.UserName, users.UserPass
FROM 
  "expensesShares" as shares
JOIN 
  users as users ON users.UserID = shares.UserID
WHERE "ExpID" = ?
`

type GetSharesRow struct {
	ExpensesShare ExpensesShare
	User          User
}

func (q *Queries) GetShares(ctx context.Context, expid int64) ([]GetSharesRow, error) {
	rows, err := q.db.QueryContext(ctx, getShares, expid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSharesRow
	for rows.Next() {
		var i GetSharesRow
		if err := rows.Scan(
			&i.ExpensesShare.ExpShareID,
			&i.ExpensesShare.ExpID,
			&i.ExpensesShare.UserID,
			&i.ExpensesShare.Share,
			&i.ExpensesShare.Calculated,
			&i.User.UserID,
			&i.User.UserName,
			&i.User.UserPass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertShare = `-- name: InsertShare :execresult
INSERT INTO "expensesShares"(
  "ExpID", "UserID", "Share", "Calculated"
)
VALUES(?, ?, ?, ?)
`

type InsertShareParams struct {
	ExpID      int64
	UserID     int64
	Share      string
	Calculated string
}

func (q *Queries) InsertShare(ctx context.Context, arg InsertShareParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertShare,
		arg.ExpID,
		arg.UserID,
		arg.Share,
		arg.Calculated,
	)
}

const updateShare = `-- name: UpdateShare :execresult
UPDATE expensesShares
SET "UserID" = ?, "Share" = ?, "Calculated" = ?
WHERE "ExpShareID" = ?
`

type UpdateShareParams struct {
	UserID     int64
	Share      string
	Calculated string
	ExpShareID int64
}

func (q *Queries) UpdateShare(ctx context.Context, arg UpdateShareParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateShare,
		arg.UserID,
		arg.Share,
		arg.Calculated,
		arg.ExpShareID,
	)
}
