// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shares.sql

package repository

import (
	"context"
)

const getShares = `-- name: GetShares :many
SELECT 
  shares.ExpShareID, shares.ExpID, shares.UserID, shares.Share, users.UserID, users.UserName, users.UserPass
FROM 
  "expensesShares" as shares
JOIN 
  users as users ON users.UserID = shares.UserID
WHERE "ExpID" = ?
`

type GetSharesRow struct {
	ExpensesShare ExpensesShare
	User          User
}

func (q *Queries) GetShares(ctx context.Context, expid int64) ([]GetSharesRow, error) {
	rows, err := q.db.QueryContext(ctx, getShares, expid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSharesRow
	for rows.Next() {
		var i GetSharesRow
		if err := rows.Scan(
			&i.ExpensesShare.ExpShareID,
			&i.ExpensesShare.ExpID,
			&i.ExpensesShare.UserID,
			&i.ExpensesShare.Share,
			&i.User.UserID,
			&i.User.UserName,
			&i.User.UserPass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
