assets: "./assets/"
port: 8081
postgres:
  user: expdbuser
  pass: thepass
  db: thedb
  host: /home/esilva/Desktop/projetos/expenses/src/pgImage/pgSocket/
  port: 5432
migrationsPath: "file://expenses/repo/pgdb/migrations/"
migCustomScripts: "./expenses/repo/pgdb/migrations/custom/"
