assets: "./assets/"
port: 8081
postgres:
  user: expdbuser
  pass: thepass
  db: thedb
  host: 127.0.0.1
  port: 5431
migrations_path: "file://expenses/repo/pgdb/migrations/"
mig_custom_scripts: "./expenses/repo/pgdb/migrations/custom/"
