assets: "./assets/"
port: 8081
postgres:
  user: expuser
  pass: exppass
  db: expdb
  host: 127.0.0.1
  port: 5431
migrations_path: "file://expenses/db/migrations/"
mig_custom_scripts: "./expenses/db/migrations/custom/"
